name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - me-things

jobs:
  buildJava14:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Run unit tests
      run: ./gradlew clean cleanTest test
    - name: Trigger BE build
      if: ${{ github.repository == 'Blockzilla101/Mindustry' }}
      run: |
        git clone --depth=1 --branch=master https://github.com/Blockzilla101/MindustryBuilds ../MindustryBuilds
        cd ../MindustryBuilds
        echo version ${GITHUB_RUN_NUMBER}
        git tag ${GITHUB_RUN_NUMBER}
        git config --global user.name "Build Uploader"
        git push https://Blockzilla101:${{ secrets.API_TOKEN_GITHUB }}@github.com/Blockzilla101/MindustryBuilds ${GITHUB_RUN_NUMBER}
